name: Test Axiom

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Check Axiom files
        run: |
          pwd
          ls -la
          echo "----- src -----"
          ls -la src
          echo "----- src/axiom -----"
          ls -la src/axiom

      - name: Run Axiom
        run: python -m src.axiom.axiom