name: Test Axiom

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Show project structure
        run: |
          echo "CURRENT DIRECTORY:"
          pwd
          echo
          echo "ROOT:"
          find . -maxdepth 3 -type f | sort
          echo
          echo "PYTHON:"
          python --version

      - name: Run Axiom
        run: python -m src.axiom.axiom